public class EnumValue {
    public static void main(String[] args) {
        Direction[] directions = Direction.values();

        for(Direction d : directions) {
            System.out.println(d.name());
        }
        Direction d1 = Direction.valueOf("EAST");
        System.out.println(d1.name());

        System.out.println(d1.ordinal());
    }
}

// values() --> We can iterate in this enum ==> this method is generated by compiler
// valueOf() --> Convert a String into a enum Consonant ==> this method is generated by compiler
// name() vs toString()
// ordinal()
// toString(), equals(), hashCode()
// enum can not extend other classes as it already extends enums class internally amnd multiple inheritance is not supported in java but can implements multiple classes

enum Direction {
    NORTH,
    SOURTH,
    EAST,
    WEST;
    @Override
    public String toString() {
        return this.name() + " Direction";
    }
    //Can't Override name()
    // @Override
    // public String name() {
    //     return this.name() + " Direction";
    // }

}
